### ISSUE TITLE
on redux, not seeing CELERYD_PREFETCH_MULTIPLIER

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#107]
Getting this error when I try to launch (locally)... (doesn't happen on master, does on redux):
```
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 220, in getarg
    raise ValueError('{0!r}: {1}'.format(ns_key, exc))
ValueError: 'CELERYD_PREFETCH_MULTIPLIER': invalid literal for int() with base 10: ''
```
Seems like that constant was removed in [commit 67857](https://github.com/nextml/NEXT/commit/67857229a18a8bb7886160fd2273568d819ec082), but I'm still getting the error if I add it back in. Also, celery docs say it defaults to 4 anyway.

**Comment by kgjamieson** [comment]
It was removed from constants.py and moved to be an environmental variable set by next_ec2.py so that all these important performance constants are in one place. Are you using the ec2 script to launch or running locally?

**Comment by dconathan** [comment]
Running locally.

**Comment by dconathan** [comment]
I'm guessing then something has to be set in the docker-compose.yml file?

**Comment by kgjamieson** [comment]
In that commit you sent above you can see which env variable was added to next_ec2.py. There is a section in next_ec2.py that constructs the docker-compose.yml file using environmental variables - that is the place to mirror

**Comment by dconathan** [comment]
Great!  Fixed by adding
```
CELERY_ASYNC_WORKER_PREFETCH=0
```
To `environment` section of `minionworker` in docker-compose.yml and docker-compose.yml.pre

**Comment by dconathan** [comment]
Created a [pull request](https://github.com/nextml/NEXT/pull/109) that fixes this issue.
