### ISSUE TITLE
"No module named yaml" - not loading correct docker_base_image?

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#108]
Again, running locally on redux branch:

When I try to launch an experiment, get a `ImportError: No module named yaml` when [App.py](https://github.com/nextml/NEXT/blob/redux/next/apps/App.py) is called.

`pyyaml` is in the [requirements.txt](https://github.com/nextml/NEXT/blob/redux/next/base_docker_image/requirements.txt) in [base_docker_image](https://github.com/nextml/NEXT/tree/redux/next/base_docker_image), so not sure why this would be.

Learning from the last issue, I compared the ec2 [docker-compose](https://github.com/nextml/NEXT/blob/master/ec2/templates/docker-compose.yml) to the local [docker-compose](https://github.com/nextml/NEXT/blob/redux/local/docker-compose.yml):
The former has:
```
minionworker:
  build: next/base_docker_image
```
The latter has:
```
minionworker:
  build: /home/ubuntu/NEXT/next/base_docker_image
```
(same for `nextbackenddocker`, which is also showing the import error)
So I thought this was the issue... calling the wrong requirements file or something... tried playing around with a few things with no luck.

**Comment by kgjamieson** [comment]
What is your procedure for running locally? 
I'm not sure if anyone has been maintaining "/local" - I didn't know it existed for redux until now. 
If you look at next_ec2.py and what it does when its launching a machine on ec2, that procedure should be mirrored locally.

Inspecting setup.sh in the ec2 folder, it installs "yaml" so presumably there is both "yaml" and "pyyaml", not sure if this is relevant.

**Comment by crcox** [comment]
My fork is way out of date and I'm getting merge conflicts trying to update
so that I can submit a pull request... I'll just nuke my fork and start
over... But in the meantime...

There is no python module called "yaml", only pyyaml, so the setup.py
should be changed, I believe.

pip install yaml --user
Collecting yaml
  Could not find a version that satisfies the requirement yaml (from
versions: )
No matching distribution found for yaml


pip install pyyaml --user
Requirement already satisfied (use --upgrade to upgrade): pyyaml in
./.local/lib/python2.7/site-packages

**Comment by dconathan** [comment]
@kgjamieson My procedure is as is described in the /local [readme](https://github.com/nextml/NEXT/blob/redux/local/README.md)... you're right it does not seem like this folder has been kept up to date (I see no difference between it and the version in the master branch).

**Comment by dconathan** [comment]
Yeah the only place I see the difference is in the ec2 [setup.sh](https://github.com/nextml/NEXT/blob/redux/ec2/templates/setup.sh), but as @crcox said, the package is called pyyaml not yaml so I'm not so sure this is the source of the issue.  I'll keep digging...

It's also weird that is only seems to be yaml causing the issue.  I tried adding in `import package` for a bunch of other packages in the [requirements](https://github.com/nextml/NEXT/blob/redux/next/base_docker_image/requirements.txt) and I'm not getting import errors for those.

**Comment by dconathan** [comment]
Also tried adding: `python-yaml` to the [Dockerfile](https://github.com/nextml/NEXT/blob/master/next/base_docker_image/Dockerfile), which should install the ubuntu package containing that module... no luck

**Comment by dconathan** [comment]
@lalitkumarj figured it out.  The redux version was trying to launch on the docker images built with the master version... I deleted the docker images and rebuilt them using the redux Dockerfile and it works now.
