### ISSUE TITLE
database not functioning with custom TargetManager

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#121]
I created a custom target manager that doesn't use the existing database infrastructure.  Basically, it has methods that read from a pickle file and csv file for feature data and text data, respectively (this is a temporary thing designed to *hopefully* interact with my App in the same way that my scaled up spark target manager will)...

Anyway I'm getting this weird error, hopefully it is not indicative of something fundamentally flawed with my approach...

The error occurs when I try to load the experiment list page.  The experiment is able to launch and an exp_uid is indeed created (along with a query link), but I guess now the exp_uid isn't showing [here](https://github.com/nextml/NEXT/blob/master/next/api/resource_manager.py#L114)

Is this related to my Target Manager or did I just miss something?

```
[34mnextbackenddocker_1 | [0m[2016-06-16 20:27:28 +0000] [12] [DEBUG] GET /dashboard/experiment_list
[32mmongodb_1           | [0m2016-06-16T20:27:28.965+0000 I NETWORK  [initandlisten] connection accepted from ***.***.**.*:***** #36 (32 connections now open)
[34mnextbackenddocker_1 | [0mException on /dashboard/experiment_list [GET]
[34mnextbackenddocker_1 | [0mTraceback (most recent call last):
[34mnextbackenddocker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
[34mnextbackenddocker_1 | [0m    response = self.full_dispatch_request()
[34mnextbackenddocker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
[34mnextbackenddocker_1 | [0m    rv = self.handle_user_exception(e)
[34mnextbackenddocker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
[34mnextbackenddocker_1 | [0m    return original_handler(e)
[34mnextbackenddocker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
[34mnextbackenddocker_1 | [0m    reraise(exc_type, exc_value, tb)
[34mnextbackenddocker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
[34mnextbackenddocker_1 | [0m    rv = self.dispatch_request()
[34mnextbackenddocker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
[34mnextbackenddocker_1 | [0m    return self.view_functions[rule.endpoint](**req.view_args)
[34mnextbackenddocker_1 | [0m  File "/next_backend/next/dashboard/dashboard.py", line 39, in experiment_list
[34mnextbackenddocker_1 | [0m    for exp_uid in rm.get_app_exp_uids(app_id):
[34mnextbackenddocker_1 | [0m  File "/next_backend/next/api/resource_manager.py", line 102, in get_app_exp_uids
[34mnextbackenddocker_1 | [0m    exp_uids.append(str(doc['exp_uid']))
[34mnextbackenddocker_1 | [0mKeyError: 'exp_uid'
```

**Comment by dconathan** [comment]
Never mind, I just checked and am apparently getting this same error with the normal target manager...

**Comment by dconathan** [comment]
In case you're curious, this seems to just have stemmed from an error from rebuilding the docker images. I rebuilt them again and the error went away.

**Comment by dconathan** [comment]
Sorry to close and reopen.  I've narrowed down the problem slightly.  The reason the error kept happening was because the "failed" experiment was still in the history, so I'm never able to launch a new experiment until I rebuild the images (unless there's a faster way to delete experiments...)

Anyway, the "doc" that is throwing the `KeyError` has the following keys:
`[u'_id', u'n']`
When it should have
`[u'exp_uid', u'git_hash', u'args', u'app_id', u'start_date', etc...]`

So something is going awry during the [initExp of App.py](https://github.com/nextml/NEXT/blob/redux/next/apps/App.py#L46-L84) or my Application... but I can't pinpoint it...

Any ideas what it might be?

**Comment by dconathan** [comment]
Maybe it was obvious after the last post, but it's definitely [this line](https://github.com/nextml/NEXT/blob/redux/next/apps/App.py#L60) that's not working:

If I print the result of `self.butler.experiment.get()` I just get the two keys/values from the previous comment...

**Comment by kgjamieson** [comment]
Check out App.py for how to delete experiments

**Comment by dconathan** [comment]
Thanks I was looking for something like that!

Apparently, I can still add stuff manually to that doc using `self.butler.experiment.set(key='exp_uid', value=blah)`... if nothing is figured out I will try tomorrow manually setting the stuff that throw errors and see what happens...

**Comment by dconathan** [comment]
Ironically, that method for deleting experiments doesn't work because the experiments I'm trying to delete don't have an exp_uid in their doc.  I managed to delete all the other experiments though...

**Comment by dconathan** [comment]
Forced the `exp_uid` into the doc by putting `butler.experiment.set(key='exp_uid', value=exp_uid)` in the initExp of my App.  I can now see the experiment list/dashboard, but of course can't get a query for similar reasons.  Now the [args returned by this](https://github.com/nextml/NEXT/blob/redux/next/api/resource_manager.py#L202) is a `None`...

**Comment by dconathan** [comment]
Thought it might have been my large files exploding the database but I tried it with very small files (<1mb) and same thing.

**Comment by dconathan** [comment]
I think I solved my problem - I think it had to do with large files exploding the database after all.
