### ISSUE TITLE
Remove redundant use of app name in apps

### ISSUE THREAD

**Issue by daniel3735928559** [nextml/NEXT#137]
Right now, one of the most annoying features about copying an existing app is changing the app name everywhere it appears in the app directory.  We could improve this by using relative imports and by renaming NameOfApplication.py to `App.py` or `myApp.py` or similar (and likewise for NameOfApplication.yaml), leaving the app name appearing only in the folder name and in the init of myApp.py.

**Comment by dconathan** [comment]
I think we can close this right?

**Comment by stsievert** [comment]
Yeah, it's closed by #155
