### ISSUE TITLE
Document steps for running NEXT locally

### ISSUE THREAD

**Issue by daniel3735928559** [nextml/NEXT#138]
We wish to run NEXT locally at least on OS X.

**Comment by dconathan** [comment]
I wrote some documentation for this at AmFam so I can help out.  The key is using [docker for mac](https://docs.docker.com/docker-for-mac/) and not "docker toolbox"

**Comment by stsievert** [comment]
That'd be helpful. I mostly want to document using NEXT locally on macOS, including which docker to download and what buttons to click. I tried earlier, I believe with Docker Toolbox.

**Comment by stsievert** [comment]
Closed with aa98bcaf8dadbf5e2c1423dcc674049768583fdc

I can now run NEXT locally, but ran into the issue of having the targets formatted correctly as described in #143.
