### ISSUE TITLE
Generate a website

### ISSUE THREAD

**Issue by scottsievert** [nextml/NEXT#15]
If we want to release this publicly, we should have an accompanying website. This website can detail the features, installation and documentation of NEXT.

GitHub offers domain hosting for stuff like this. If a new branch called `gh_pages` is created, that branch is visible at `https://kgjamieson.github.io/next`. GitHub has this process documented at [GitHub Pages].

A generated site should use a static site generator, probably [Hugo], [Jekyll] or [Pelican][Pelican] (and there are dozens of themes for each of these). There's a full list of frameworks/generators listed at [staticgen]. 

[staticgen]:http://www.staticgen.com
[Hugo]:http://gohugo.io
[Pelican]:http://blog.getpelican.com
[Jekyll]:http://jekyllrb.com
[GitHub pages]:https://pages.github.com

**Comment by lalitkumarj** [comment]
Hi

We have discussed this a  fair bit in the past. I will be working on getting a minimal Jekyll page up today - basically migrating Chris' work over and combining it with the current NEXT splash page.

**Comment by scottsievert** [comment]
I have developed a website using Sphinx that documents how to setup and use the CLI/GUI ([visible here][1]). It does not cover what NEXT is or what it can do. You're planning on making a site that covers those details, correct?

[1]:https://rawgit.com/kgjamieson/NEXT-psych/docs/_build/html/index.html

**Comment by lalitkumarj** [comment]
Yes...but I think the plan is to have those kind of instructions in the github wiki (where they are now). I'm not anti a sphinx site, but its just another body of code to maintain - and github wiki works pretty well. Also let's hold off on any more instructions until the launch scripts are a bit more finalized with the exception of the "cheat sheet" that we can develop while helping the psych people get off the ground.

I love the troubleshooting page, can you migrate that to the github wiki?

**Comment by scottsievert** [comment]
@lalitkumarj generated a website on the gh_pages branch, but there a couple issues:

- [ ] Label highlighting doesn't work and always focused on "Home"

![screen shot 2015-09-27 at 4 46 39 pm](https://cloud.githubusercontent.com/assets/1320475/10125378/6b453f00-6537-11e5-9bb1-213bd54cb9ca.png)

- [ ] Not mobile friendly. 
    - [ ] Too much header whitespace on the homepage
    - [ ] no menu/links to the other NEXT pages
    - [ ] menu header transparent

![img_1898](https://cloud.githubusercontent.com/assets/1320475/10125407/3ca44a0a-6538-11e5-9272-927ad47fc8b2.png)

**Comment by lalitkumarj** [comment]
I have no plan to fix these in the near future.
