### ISSUE TITLE
Spot instance ability

### ISSUE THREAD

**Issue by lalitkumarj** [nextml/NEXT#17]
I think the spark script has the ability to launch a spot instance. I'd like to flush this out for users.

**Comment by kgjamieson** [comment]
I don't understand how this would work. Spot instances can be killed without warning at any time. That seems like a pretty bad idea for NEXT as a service. Would this be for development only?

**Comment by stsievert** [comment]
Closed by @kgjamieson in fa742779bc850be9094e842807fe229d0c274e27
