### ISSUE TITLE
Celery not working on local

### ISSUE THREAD

**Issue by lalitkumarj** [nextml/NEXT#172]
Celery does not seem to be accepting jobs on local. I suspect some environment variables are broken.

**Comment by dconathan** [comment]
I just did a fresh clone and everything seems to be working.  I didn't rebuild my images but I don't think that would have anything to do with it.  Can you elaborate?

**Comment by stsievert** [comment]
This might be docker versioning -- Lalit updated yesterday and I haven't updated for a while. I'm on Docker 17.03.0-ce-mac2 and local works fine for me.

**Comment by lalitkumarj** [comment]
Same docker version...Rudi ran into the same issue. Going to bed. Will
tackle tomorrow.

**Comment by dconathan** [comment]
me:
Docker version 17.03.0-ce, build 60ccb2265b

**Comment by dconathan** [comment]
Not sure if this is related, but occasionally I need to remove the containers (`docker rm $(docker ps -aq)').  (this deletes all experiments)

**Comment by liamim** [comment]
Fixed by #198.
