### ISSUE TITLE
MTurk requiring HTTPS link

### ISSUE THREAD

**Issue by mllewis** [nextml/NEXT#178]
I'm trying to run Next through the turk API, which requires https rather than http links, and so I can't link to my next experiment because the EC2 server isn't setup for https. Is it possible to change my EC2 instance to be https?

Thanks!

**Comment by stsievert** [comment]
It looks you need to use an [HTMLQuestion][2], not an [ExternalQuestion][1]. HTMLQuestions allow you to input any HTML, including an HTTP link. ExternalQuestions requires the link to be HTTPS, and I think that's the error that you're seeing.

Does that resolve this issue?

[1]:http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ExternalQuestionArticle.html
[2]:http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_HTMLQuestionArticle.html

**Comment by mllewis** [comment]
Thanks! I will try that.

**Comment by stsievert** [comment]
Can this issue be closed?

**Comment by mllewis** [comment]
Yes, thanks!
