### ISSUE TITLE
ssh into AWS

### ISSUE THREAD

**Issue by remcinerney** [nextml/NEXT#179]
Is there a convenient way to ssh into an AWS cluster using the next_ec2 script? (I'm trying to do this so I can play around with the docker containers... but maybe there is a better way to do this)

Thanks

**Comment by stsievert** [comment]
"Python next_ec2 docker_login [machine-name]". This will look for some variables in your environment for AWS secret access key. Mostly it ssh's you in then puts you in the directory "/usr/local/next-discovery" (I think, I need to verify).

If you launch via AMI I'm not sure if the next_ec2 script works as expected.
