### ISSUE TITLE
Debrief and Instruction accept html

### ISSUE THREAD

**Issue by lalitkumarj** [nextml/NEXT#27]
April wants to be able to input arbitrary html. I think in addition to instructions, we need an "introduction" panel which is basically the modal. The alternative is custom query pages on a forked version...

**Comment by scottsievert** [comment]
Is this fixed? Can we know accept arbitrary HTML or does it still have to be parsed?

**Comment by kgjamieson** [comment]
This is closed, yet?

**Comment by scottsievert** [comment]
Yes. It's on NEXT-psych as [issue 11](https://github.com/kgjamieson/NEXT-psych/issues/11)
