### ISSUE TITLE
Database backup to local file

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#30]
NEXT currently relies on AWS S3 to save backups of the database. For simplicity we should give the user the opportunity to download the database to a file. That is, for any running NEXT system, there should be a URL (with appropriate security keys given) that returns a zipped version of the entire database and everything necessary to relaunch the system on another machine. 

In addition, upon launch of a NEXT system, perhaps we can have a URL with a very simple HTML page that allows us to upload the same file as above to restore the NEXT database.

This is all possible through S3 and the scripts but we should give people the opportunity to save and restore to and from a local file.

**Comment by lalitkumarj** [comment]
This is partially done through an endpoint /api/database/backup. I haven't added the ability to restore the db yet...it's coming soon.

**Comment by kgjamieson** [comment]
Can we prioritize this? I'd like to start using this functionality
