### ISSUE TITLE
dashboard enhancements: descriptive text to sections

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#41]
Add descriptions of each section describing what is being plotted, how its being calculated, and how/why its useful for the users to look at

**Comment by scottsievert** [comment]
I implemented question marks on the dashboard to explain what each plot is.

@kgjamieson @lalitkumarj I am not familiar enough with these plots to add descriptive text -- I'll leave it up to you. The lines that need to be changed are in [next/apps/PoolBasedTriplet/dashboard/PoolBasedTriplet.html][1] (and likewise for DuelingBandits and TupleBandits).

[1]:https://github.com/nextml/NEXT/blob/dev/next/apps/PoolBasedTripletMDS/dashboard/PoolBasedTripletMDS.html#L83

![screen shot 2015-11-10 at 7 34 26 pm](https://cloud.githubusercontent.com/assets/1320475/11081414/15fc372e-87e2-11e5-8d43-9a8c5b4f7d88.png)
![screen shot 2015-11-10 at 7 35 01 pm](https://cloud.githubusercontent.com/assets/1320475/11081424/2a211f80-87e2-11e5-9741-eb8858bb1407.png)

**Comment by kgjamieson** [comment]
Done for all apps now
