### ISSUE TITLE
Cleanup Protoype Code

### ISSUE THREAD

**Issue by lalitkumarj** [nextml/NEXT#46]
This is on the apps. @kgjamieson can you comment on this a bit more?

**Comment by kgjamieson** [comment]
The structure of inheriting the base object is fine, but the actual
docstrings about expected input/output is out of date.

**Comment by kgjamieson** [comment]
prototype.py inside the app folder is supposed to be the interface that all the algorithms must implement, in fact, they inherit it. Thus, prototype.py docstrings should be copies of those in the algorithms themselves
