### ISSUE TITLE
Query page CSS

### ISSUE THREAD

**Issue by lalitkumarj** [nextml/NEXT#48]
Use Bootstrap/Image responsive.

**Comment by lalitkumarj** [comment]
Daniel basically has a version of this working. Daniel, can you go ahead and push your changes on all three app types after testing?

**Comment by daniel3735928559** [comment]
Yeah I think I've got it figured out, so I'll do it Monday.  I'll need to rope in someone with a phone to test these too at some point.

**Comment by lalitkumarj** [comment]
I think all of this is more or less working. Again, mostly an app level issue.
