### ISSUE TITLE
When launching experiment the quote character is not converted to HTML

### ISSUE THREAD

**Issue by scottsievert** [nextml/NEXT#59]
In [launch_experiment.py], there's an issues where the quote character `"` is not replaced with the HTML character `&quot;`. This can probably be fixed somewhere around line 93 (see link).

The python package [HTML] looks like it can be of use. It can probably "HTMLify" a string.

[HTML]:https://pypi.python.org/pypi/html/
[launch_experiment.py]:https://github.com/nextml/NEXT/blob/master/examples/launch_experiment.py#L93

**Comment by lalitkumarj** [comment]
Did you test it?

**Comment by scottsievert** [comment]
Yup.

![screen shot 2015-11-21 at 11 04 43 pm](https://cloud.githubusercontent.com/assets/1320475/11322165/4b52c18e-90a4-11e5-95ec-1c22c5a19191.png)
