### ISSUE TITLE
Workflow documentation

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#62]
It might be useful to writeup a little something describing the workflow in developing algs for NEXT. That is, in the terminal
- Use one tab to rsync up 
- docker_login in another tab, remove containers and docker-compose up
- In another tab have the test script that points at the dev machine

I could write something up, does anyone think this could be useful?

**Comment by scottsievert** [comment]
+1. This was one of my biggest barriers when starting to develop. 

Also, I'd point where to look for documentation on how to develop an algorithm (what functions, what classes, etc). Info.py has the required documentation (I think) but we should expose that and make it easy to find.

**Comment by kgjamieson** [comment]
Work in progress: https://github.com/nextml/NEXT/wiki/Developer-Guide

Feedback appreciated
