### ISSUE TITLE
Document example files

### ISSUE THREAD

**Issue by lalitkumarj** [nextml/NEXT#63]
The example files for launching experiment in the examples should be documented fully.

**Comment by lalitkumarj** [comment]
@scottsievert: Scott, how is this going? Can we close this issue?

**Comment by scottsievert** [comment]
I believe it's done but it probably needs review. A sample is in the examples directory (every example file has been commented).

https://github.com/nextml/NEXT/blob/dev/examples/cartoon_cardinal/experiment_cardinal.py

**Comment by lalitkumarj** [comment]
Looks good.
