### ISSUE TITLE
Convert test scripts to use the launch experiment script for consistency

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#67]
The original thinking was that the test scripts showed barebones functionality but I'm not sure how much sense this makes as the next thing someone wants to do after testing the experiment is launch one, and that requires a completely different use pattern. Maybe it makes sense to append a flag to the launch_experiment script for testing so that it will launch the experiment (including images and stuff) and then pound it with simulated traffic.

**Comment by kgjamieson** [comment]
This seems totally possible in redux branch. There has been talk about pointing hte script to a context and target set and its uploaded to ec2 and then s3 serverside, nothing is done client side

**Comment by lalitkumarj** [comment]
I think that the whole testing framework should be rewritten. I am going to close this issue as it is a bit dated.
