### ISSUE TITLE
Comment options in launch script

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#7]
While the launch script examples work its not obvious how to change the behavior even a little without digging into the code. 

For example, in dueling bandits its not obvious that to not have a "context" all you do is comment it out or simply not attach it the experiment object. And how to switch the context between an image or text

**Comment by lalitkumarj** [comment]
This is incredibly important. There are a lot of options and it really can vary by experiment. In particular there is some non trivial logic around how to handle targets.

**Comment by kgjamieson** [comment]
Duplicate of #63
