### ISSUE TITLE
Ensure indexes for mongoDB in the mongo_backup script.

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#85]
Indexes are critical for speedy queries to the database. But they should be placed before any data goes in (and queries are made). A convenient place to have indexes built is in the mongodb_backup script since it is run everytime the containers are started and doesn't really do anything else.

**Comment by kgjamieson** [comment]
Clearly this means moving all the index ensures from the initExp and init targetMapping scipts to this one location

**Comment by kgjamieson** [comment]
Indexes are

**Comment by liamim** [comment]
Most of this doesn't really apply now that the db refactor is done. Additionally, adding indexes in initExp is perfectly fine. The one issue here that still needs to be addressed is that indexes aren't built for targets. We should really do that; it has the potential to vastly speed up target accesses.
