### ISSUE TITLE
Empty caption is replaced by the target index

### ISSUE THREAD

**Issue by stsievert** [nextml/NEXT#91]
While launching a New Yorker experiment, we had an empty caption (example below). This empty caption was replaced by the index (shown by the line number in the example).

```
line # : content
...
6776   : This is a caption!
6777   : 
6778   : This is a caption!
...
```

This example was under the dev branch, not the redux branch.

**Comment by liamim** [comment]
Tested with `CardinalBandits` and the `cartoon_cardinal` example. Could not reproduce.
