### ISSUE TITLE
Downloading participant data/etc for large experiments is slow

### ISSUE THREAD

**Issue by scottsievert** [nextml/NEXT#93]
For the New Yorker experiment with 100k participant responses, I haven't been able to download the participant data. I can download much smaller datasets on the same machine, and experiments with roughly 30k responses takes a moderately long time (less than 30min).

I believe this problem is born by the fact that in the api directory, [participant.py][file] we have a triple nested for-loop:

``` python
        for participant, responses in participant_responses.iteritems():
            for response in responses:
                for target_index in response['target_indices']:
                    target_index['target'] = targetmapper.get_target_data(exp_uid,
                                                                          target_index['index'])
```

Is there any way we can get the participant data without making a database call each time?

[file]:https://github.com/nextml/NEXT/blob/master/next/api/resources/participants.py

**Comment by kgjamieson** [comment]
I think I fixed this on the dev branch. Essentially it pulls the mapping
once and then assigns each index. But its still slow

**Comment by lalitkumarj** [comment]
This issue will dissappear completely on the redux branch. Good catch
though, let's make sure to look out for it.

**Comment by scottsievert** [comment]
Is it fixed on the redux branch? I see the same code on both branches.

**Comment by kgjamieson** [comment]
Fixed in redux branch
